spring:
  application:
    name: ce-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://ce-auth-ms
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: mySecretKey