spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ce-auth-ms
              uri: lb://ce-auth-ms
              predicates:
                - Path=/ce-auth-ms/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: MY-JWT-SECRET